spring:
  application:
    name: userservice
  datasource:
    #    url: jdbc:mysql://localhost:3306/airlinereservation
    #    username: root
    #    password: Anju@1234
    url: jdbc:mysql://localhost:3306/anand15
    username: root
    password: anand
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8585

reservation.url: https://airline-reservation-sys.herokuapp.com/reservations/byPerson/